In [ ]:
**============EDA===============

1) pandas : data frame or data applicatons 
2) numpy  : Numerical python for math operation 
3) matplotlib     : for plots graphs 
4) seaborn        : for plots graphs
5) bokhe          : for plots
6) plotly         : for plots


===============ML===============

1) scikit learn (sklearn)    : ML models 
2) stats                     : statical models 


==============Data retrival from sql scrapping============

9) sqlite                : connect with database
10) Beutiful soap        : scrap the data from website
11) websocket            : scrap


===============Deep learning/ computer vision=================

12) tensorflow             : google
13) keras                  : DL models
14) Open CV                : image operation 
15) pillow (PIL)           : image operation 
16) pytorch                : devloped a facebook
17) pretrained model       :
       VGG16
       Mobilenet
       RESENET
       RCNN
       MASKRCNN
       FASTERCNN
       YOLO

================= NLP- Natural language process===============
18) NLTK        : Natural language process
19) scipy  
20) word 2vec (How words will convert into vector) :
21) Glove
22) wordcloud
============== Hugging face==========
23) Transformers      : BERT is this google properties - 
-----BERT full form - Bidirectional Encoder representations from Transformers------ 

================GenAI models ==============
24) OpenAI + Microsoft  : GPT models
25) Google              : Gemini        
25) Amazon              : MetaAI
26) Meta facebook       
27) Apple

LLAMA
GEMMA
Dalle-E
T5

ALL ARE HAVING DIFFERENT DIFFERENT PACKAGE

===============lANGCHAIN==============
29) langchain is a framework 

===========Deployment / applications============
30) Flask
31) streamlite
32) Django

================Mlops ===============
33) Mflow  
34) kubeflow   
35) Azure AI services   : azure pacakges
36) GCP  : GCP package ** 

**step1
create a data frame**

In [ ]:
- we will create a dataframe using list 

- we will create a dataframe using dictionary 
 

In [5]:
import pandas as pd 

d1=pd.DataFrame()
d1

Empty DataFrame
Columns: []
Index: []

In [6]:
type(d1)

pandas.core.frame.DataFrame

**STEP-2**
**provide the data**

In [7]:
names=['sameer','pankaj','shubham']
pd.DataFrame(names)

0
0   sameer
1   pankaj
2  shubham

In [77]:
names=['sameer','pankaj','shubham']
age=[20,25,26]
city=['Hyd','mumbai','pune']
data=(zip(names,age,city))
pd.DataFrame(data)

0   1       2
0   sameer  20     Hyd
1   pankaj  25  mumbai
2  shubham  26    pune

**step - 3 Provide the column names**

In [16]:
names= ['sameer','pankaj','shubham']
pd.DataFrame(names,
                  columns= ['Names'])

Names
0   sameer
1   pankaj
2  shubham

In [81]:
names=['pankaj','shubham','sam']
age=[20,25,26]
city=['Hyd','ECIL','Blr']
No=['1','2','3','4']
data=zip(No,names,age,city)
cols=['No','names','age','city']
pd.DataFrame(data,columns=cols)

No    names  age  city
0  1   pankaj   20   Hyd
1  2  shubham   25  ECIL
2  3      sam   26   Blr

**step-4**


**providing index**

In [20]:
names=['tarun','surender','mohit']
age=[20,25,26]
city=['Hyd','ECIL','Blr']


data=zip(names,age,city)
ix=['A','B','C']
cols=['Names','age','city']

pd.DataFrame(data,
            index=ix,
            columns=cols)

Names  age  city
A     tarun   20   Hyd
B  surender   25  ECIL
C     mohit   26   Blr

In [ ]:
- create a dataframe 

- provide the data

- add the column

- provide the column names

- provide the index

**Step - 5**

**add a new column on existing data frame**

In [1]:
# create a dataframe 
# name
# age 
# city

import pandas as pd
name=['sameer','nagesh','madhur']
age=['22','23','24']
city=['dhule','ap','nagpur']
data=['name','age','city']
pd.DataFrame(zip(name,age,city))

0   1       2
0  sameer  22   dhule
1  nagesh  23      ap
2  madhur  24  nagpur

- if you want  to add new column 
- first check how many rows are there
- for example in above dataframe we have 3 rows
- your new column also should have 3 rows
- suppose i want create a new column : **salary**
- make a list with 3 values
- salary [100000,200000,300000]
- **Syntax**: Dataframe [column]=list of vlaues

- salary =[100000,200000,300000]
- df['salary']=salary

In [47]:
df['salary']=[]

NameError: name 'df' is not defined

In [54]:
import pandas as pd

name=['sameer','nagesh','madhur']
age=['22','23','24']
city=['dhule','ap','nagpur']
salary=[100000,200000,300000]
pd.DataFrame(zip(name,age,city,salary))

0   1       2       3
0  sameer  22   dhule  100000
1  nagesh  23      ap  200000
2  madhur  24  nagpur  300000

**Use case-1**

- create a empty dataframe first 
- create 3 list using list compheresion
- list1 = a values from 1 to 10
- list2 = square of  to
- list cube of to
- Finally make a dataframe

In [74]:
import pandas as pd 
df1=pd.DataFrame()

l1=[i for i in range(1,10)]
l2=[i**2 for i in range(1,10)]
l3=[i**3 for i in range(1,10)]

df1['X']=l1
df1['Y']=l2
df1['Z']=l3
df1
    

X   Y    Z
0  1   1    1
1  2   4    8
2  3   9   27
3  4  16   64
4  5  25  125
5  6  36  216
6  7  49  343
7  8  64  512
8  9  81  729

**Update the already existed column**`

- create a new column
          - creating a new list salary = [1000,2000,3000]

          - df['s']

          - creating a new column the column name is our choice 

- update existing column are same way only
    - here also we need a make a list of values = number of rows
    - while updating existing column
    - we need to provide already existed column name only
    - df['z']=list of values

In [82]:
Z=[i**4 for i in range(1,10)]
df1['Z']=Z
df1

Y     Z
0   1     1
1   4    16
2   9    81
3  16   256
4  25   625
5  36  1296
6  49  2401
7  64  4096
8  81  6561

**Step-1**

**Drop the column**

In [56]:
df1.columns

Index(['x', 'Y', 'Z'], dtype='object')

- If you want to drop a specific column
- we will use drop method
- we already know anbout difference between keywords and methods
- keywords use directly
- methods will use with corresponding dataframe
- **Method name : drop**

df1.drop()

- Column : which colmn you want to drop 
- axis Represents the specified value is a row or column

  - axis = 0 means rows

  - axis = 1 means column
 
  - by default axis = 0

-inplace : will provide overwrite the dataframe or not

  - inplace = True, this indicates overwrites the dataframe

    - inplace = False, this indicates modified the dataframe will be use when you provide the new variable for the operation
  

In [53]:
df1.drop('X')
# we are not providing a axis 
# it assuing the provided value is a row 
# by default axis = 0 

KeyError: "['X'] not found in axis"

In [75]:
df1.drop('X',axis=1,inplace = True)
df1

#after this in a new cell type df1
#you will see original dataframe
#

Y    Z
0   1    1
1   4    8
2   9   27
3  16   64
4  25  125
5  36  216
6  49  343
7  64  512
8  81  729

**step-8**

**Drop the row**

- drop the colulmn and drop the rows both are similar only

- the only differrent is axis

- axis =0 represents axis

- by default axis=0 available

- which means if we provided any balue it will represent rows only


In [16]:
# Dataframe : df1

import pandas as pd 
df2=pd.DataFrame()

l1=[i for i in range(1,10)]
l2=[i**2 for i in range(1,10)]
l3=[i**3 for i in range(1,10)]

df2['values']=l1
df2['Cubes']=l2
df2['Squares']=l3
df2
    

values  Cubes  Squares
0       1      1        1
1       2      4        8
2       3      9       27
3       4     16       64
4       5     25      125
5       6     36      216
6       7     49      343
7       8     64      512
8       9     81      729

In [18]:
df2.drop(4)

# if we run this we will get error
# by default axis=0 which represent about rows 
# But 'number' is a column
# if you want to drop row, the provide the rows index

values  Cubes  Squares
0       1      1        1
1       2      4        8
2       3      9       27
3       4     16       64
5       6     36      216
6       7     49      343
7       8     64      512
8       9     81      729

In [19]:
# multiple rows
# multiple column keep always in list
df2.drop([4,8])

values  Cubes  Squares
0       1      1        1
1       2      4        8
2       3      9       27
3       4     16       64
5       6     36      216
6       7     49      343
7       8     64      512

In [22]:
df2.columns[[0,1]]

Index(['values', 'Cubes'], dtype='object')

In [20]:
df2.drop([0,1],axis=1)
#[0,1]  index
#axis=1,column 
# error

KeyError: '[0, 1] not found in axis'

**Step-9**

**How to select to the column**

In [36]:
import pandas as pd
df2=pd.DataFrame()
l1=[i for i in range(1,10)]
l2=[i**2 for i in range(1,10)]
l3=[i**3 for i in range(1,10)]
l4=[i**4 for i in range(1,10)]

df2['Number']=l1
df2['values']=l2
df2['Cubes']=l3
df2['Squares']=l4
df2
    

Number  values  Cubes  Squares
0       1       1      1        1
1       2       4      8       16
2       3       9     27       81
3       4      16     64      256
4       5      25    125      625
5       6      36    216     1296
6       7      49    343     2401
7       8      64    512     4096
8       9      81    729     6561

In [37]:
df2['values']

0     1
1     4
2     9
3    16
4    25
5    36
6    49
7    64
8    81
Name: values, dtype: int64

In [38]:
df2[['values']]

values
0       1
1       4
2       9
3      16
4      25
5      36
6      49
7      64
8      81

In [39]:
type(df2[['values']])

pandas.core.frame.DataFrame

In [40]:
df2['Squares']

0       1
1      16
2      81
3     256
4     625
5    1296
6    2401
7    4096
8    6561
Name: Squares, dtype: int64

- df2['values'] series type**
- df2[['values']] series type
- df2.values : series type 


- All values comes in as array

- Array means it is a list of elements only represnts using numpy package

- Generally elements present in 4 ways

- list : basic representation

- numpy array : array with numpy package

- tensors : tenserflow package

- Torch : pytorch package

In [19]:
list1=[1,2,3,4,5]
list1

[1, 2, 3, 4, 5]

In [22]:
import numpy as np
np.array(list1)

array([1, 2, 3, 4, 5])

In [ ]:
tensor([1,2,3,4])

In [24]:
list1=[1,2,3,4,5]
list2=[10,20,30,40,50]
list1+list2

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

In [25]:
l1=np.array(list1)
l2=np.array(list2)
l1+l2

array([11, 22, 33, 44, 55])

In [27]:
 df2['values'].values

array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

In [41]:
df2['NUMBER']=df2['Number'].values
df2

Number  values  Cubes  Squares  NUMBER
0       1       1      1        1       1
1       2       4      8       16       2
2       3       9     27       81       3
3       4      16     64      256       4
4       5      25    125      625       5
5       6      36    216     1296       6
6       7      49    343     2401       7
7       8      64    512     4096       8
8       9      81    729     6561       9

**Step-10**
**Save the dataframe**

- dataframe we can save into two formats

- csv : comma separated value

- xlsx : excel format
- in order save any data

- Where you want to save : directory name

- what is the name of the file for storing

- What is the extention

- we already seen same in file handling session

In [ ]:
# case - 1 saving file at same location 
# No need to provide directory path 
# directly give only name of the file 
# and extenstion 

In [57]:
# Dataframe name : df2
# df2.to_csv('Data1.csv')
df2.to_excel('Data1.xlsx')

**step-11  How to rea a dataframe**

In [47]:
import pandas as pd
pd.read_csv('Data1.csv')

Unnamed: 0  Number  values  Cubes  Squares  NUMBER
0           0       1       1      1        1       1
1           1       2       4      8       16       2
2           2       3       9     27       81       3
3           3       4      16     64      256       4
4           4       5      25    125      625       5
5           5       6      36    216     1296       6
6           6       7      49    343     2401       7
7           7       8      64    512     4096       8
8           8       9      81    729     6561       9

In [58]:
import pandas as pd
pd.read_excel('Data1.xlsx')

Unnamed: 0  Number  values  Cubes  Squares  NUMBER
0           0       1       1      1        1       1
1           1       2       4      8       16       2
2           2       3       9     27       81       3
3           3       4      16     64      256       4
4           4       5      25    125      625       5
5           5       6      36    216     1296       6
6           6       7      49    343     2401       7
7           7       8      64    512     4096       8
8           8       9      81    729     6561       9

**Step-12**

**How to avoid index**

- while we save the dataframe

- automatically a new column will create

- that we need to avoid

- permission denied means close the data file from laptop

In [ ]:
# Dataframe name : f2
# save the data with out index column

pd.read_csv('Data1.csv',index=False)
pd.read_excel('Data1.xlsx',idex=False)